name: Lint

on:
  workflow_call:
    inputs:
      go-version:
        description: Go version
        required: false
        type: string
        default: '1.25.0'
    secrets:
      NETRC_CREDENTIALS:
        required: false
      GO_PRIVATE:
        required: false

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: toweray/.github/.github/actions/setup-go@master
        with:
          go-version: ${{ inputs.go-version }}

      - name: Configure private modules
        if: ${{ secrets.NETRC_CREDENTIALS != '' }}
        run: |
          go env -w GOPRIVATE=${{ secrets.GO_PRIVATE }}
          echo "${{ secrets.NETRC_CREDENTIALS }}" > ~/.netrc

      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: latest
          args: ./...
          
